### PR TITLE
Start readme

### PR DESCRIPTION
**Pull request by saschatimme**
I started a readme. @kalmarek @Joel-Dahne  please feel free to just push on this branch in case you find some time to add something :)

### CODE REVIEW

**Comment by Joel-Dahne** [comment]
What do you think about these changes?

**Comment by saschatimme** [comment]
Looks good!

**Comment by Joel-Dahne** [comment]
I couldn't get the example to run, fixed that. Also added type annotations to the method to be more clear about what it does. The example is good if we want to show that you can call Arb  directly, not very good if we want to show that it's convenient to use in general. Once we have added more convenience methods I guess we can create another example showing that.

**Review by Joel-Dahne — APPROVED** [review]
I think I'm happy with it in its current form. Anything more you want to add?

**Comment by kalmarek** [comment]
If we're to release it fast, then let's merge this

**Pull request merged**
