### PR TITLE
add badges: doi, ci, coverage

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by kalmarek** [comment]
@Joel-Dahne is `NEMO_THREADED=1` still a valid flag to turn multithreading on in Arblib.jl?

**Comment by Joel-Dahne** [comment]
> @Joel-Dahne is `NEMO_THREADED=1` still a valid flag to turn multithreading on in Arblib.jl?

Yes! It occurs here in the `__init__` function, see e.g.  [here](https://github.com/JuliaBinaryWrappers/FLINT_jll.jl/blob/main/src/wrappers/x86_64-linux-gnu.jl).

**Comment by Joel-Dahne** [comment]
I noticed that the stable documentation [link](https://kalmarek.github.io/Arblib.jl/stable) doesn't work, the dev version does work. It is some configuration issue somewhere I guess, but I'm not sure where...

**Review by Joel-Dahne — APPROVED** [review]

**Comment by kalmarek** [comment]
@Joel-Dahne This is because I've forgotten to add deploy/private DOCUMENTER_KEY;
I've added this one here, investigating how to re-trigger building of the documentation...

There're so many micro steps to get Documentation going correctly...

**Comment by Joel-Dahne** [comment]
This can be merged then right? The documentation issues are repository settings if I understand correctly?

**Comment by kalmarek** [comment]
@Joel-Dahne The link to docs should work now; I had to push additional tag (`v1.0.0+doc1`) to get this working so don't be surprised ;)

**Comment by Joel-Dahne** [comment]
@kalmarek Amazing! I can try to write an announcement on the Flint mailing list and the Julia discourse later today or tomorrow!

**Pull request merged**
