### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by kalmarek**
- [x] remove old macros
- [x] handwritten `set!`
- [x] handwritten predicates

other stuff?

### CODE REVIEW

**Comment by kalmarek** [comment]
test will fail (on purpose)

**Comment by kalmarek** [comment]
all `set!` methods in `src/constructors.jl` (lines `1:60`) should eventually go away, other than this is ready to go

**Comment by Joel-Dahne** [comment]
Great! We can merge this and I can start adding the files parsed from the documentation. I'm not experienced with CodeCov, does it give `n/a` because it's the first time it runs now?

**Comment by kalmarek** [comment]
yes, because it doesn't have baseline to compare

**Pull request merged**
