### PR TITLE
new gh actions

### PR DESCRIPTION
**Pull request by kalmarek**
just a standard maintenance

### CODE REVIEW

**Review by Joel-Dahne — APPROVED** [review]
Looks good! Now we also wont have to update the ci every time Julia makes a new release.

**Comment by Joel-Dahne** [comment]
I don't know why the 1.4 tests are listed as required though? They should not even be there?

**Comment by kalmarek** [comment]
I think this is from repo settings. I'll merge this and change what is required for merge

**Comment by Joel-Dahne** [comment]
Great!

**Pull request merged**
